### PR TITLE
Fix security vulnerability

### PR DESCRIPTION
**Pull request by jotjern**

### CODE REVIEW

**Review by junlarsen — CHANGES_REQUESTED** [review]
:skull: he's trying to escape

**Review by norawl — CHANGES_REQUESTED** [review]
👎

**Review by kharann — CHANGES_REQUESTED** [review]
This seems like hardcoding which is bad practice

**Comment by jotjern** [comment]
> This seems like hardcoding which is bad practice

Maybe we should make a table with terms related to hook med 05

**Comment by kharann** [comment]
Solved by existing patches

**Pull request closed without merging**
